# Generated by Django 4.2.3 on 2023-07-23 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_user_timezone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="timezone",
        ),
    ]
